version: '3.3'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: unless-stopped
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # Native TCP
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  app:
    build: .
    container_name: parcer_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - clickhouse-server
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  clickhouse_data:
    driver: local
